name: Azure Terraform

on:
  workflow_dispatch:

env:
  TERRAFORM_WORKING_DIRECTORY: "terraform"
  BACKEND_RESOURCE_GROUP_NAME: ${{ vars.BACKEND_RESOURCE_GROUP_NAME }}
  BACKEND_STORAGE_ACCOUNT_NAME: ${{ vars.BACKEND_STORAGE_ACCOUNT_NAME }}
  BACKEND_STORAGE_CONTAINER_NAME: ${{ vars.BACKEND_STORAGE_CONTAINER_NAME }}

jobs:
  getToken:
    uses: ./.github/workflows/oidc-azure.yml
  
  TerraformCode:
    runs-on: ubuntu-latest
    needs: getToken
    steps:
    - uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5
        terraform_wrapper: false

    - name: Terraform Init
      id: init
      run: |
        terraform init \
          -backend-config="resource_group_name=terraform" \
          -backend-config="storage_account_name=terraform006" \
          -backend-config="container_name=reuse" \
          -backend-config="key=$TF_BACKEND_KEY"
        echo 'Terraform Init completed successfully'
      working-directory: ${{ env.TERRAFORM_WORKING_DIRECTORY }}