name: Azure Terraform

on:
  workflow_dispatch:


jobs:
  getToken:
    uses: ./.github/workflows/oidc-azure.yml
  
  TerraformCode:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5
        terraform_wrapper: false